// Code generated by kanban/gen. DO NOT EDIT.

package banner

// Version ...
var Version = "v0.1.3-fix2"

// Copyright ...
var Copyright = "© 2023 - 2023 FloatTech"

// Banner ...
var Banner = "* QQ + NanoBot + Golang\n" +
	"* Version " + Version + " - 2023-10-18 14:51:18 +0900\n" +
	"* Copyright " + Copyright + ". All Rights Reserved.\n" +
	"* Project: https://github.com/FloatTech/NanoBot-Plugin"
